### PR TITLE
Initial port to Drupal 10

### PR DESCRIPTION
**Pull request by joecorall**

### CODE REVIEW

**Comment by bondjimbond** [comment]
@joecorall This is interesting -- I was on vacation last week, so didn't see this PR. Is there a particular reason you closed it?

**Comment by joecorall** [comment]
@bondjimbond - I was clicking too fast and issued the PR against this repo rather than just keeping it on the fork: https://github.com/lehigh-university-libraries/islandora_rights_statements

**Comment by bondjimbond** [comment]
Ah, no worries! How functional is your port? If it's complete, I'd love to use it myself.

**Comment by joecorall** [comment]
It's working great for us so far! It was a pretty straightforward port. We have it showing as a block in the metadata view. You can have any text field (in our case `field_rights`) display the badge using the field formatter display. If the field happens to have values that are not rights statements URIs, the text is shown. But if a valid rights statement URI is the value, the badge is shown.

Screen Shot on 2024-03-20 at 13-30-29

**Comment by bondjimbond** [comment]
That looks great. I'll give it a test myself at some point; I hope you don't mind if I have questions about implementation?

**Pull request closed without merging**
